"""feat: adding session, message tabel

Revision ID: eeb13cdc6255
Revises: 14a03aeb8902
Create Date: 2026-09-27 13:20:59.037860

"""
import sqlmodel
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eeb13cdc6255'
down_revision: Union[str, None] = '14a03aeb8902'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('generation_model_id', sa.String(), server_default='gpt-4o-mini', nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_name'), 'session', ['name'], unique=False)
    op.create_index(op.f('ix_session_project_id'), 'session', ['project_id'], unique=False)
    op.create_index(op.f('ix_session_user_id'), 'session', ['user_id'], unique=False)
    op.create_table('message',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('SYSTEM', 'USER', 'ASSISTANT', name='msgroles'), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_session_id'), 'message', ['session_id'], unique=False)
    op.drop_table('pgvector_786_25fbf57b-7df8-4b62-a211-5da0acb662ae')
    op.drop_index(op.f('ix_celery_tasksetmeta_date_done'), table_name='celery_tasksetmeta')
    op.drop_table('celery_tasksetmeta')
    op.drop_index(op.f('ix_celery_taskmeta_date_done'), table_name='celery_taskmeta')
    op.drop_table('celery_taskmeta')
    op.drop_table('pgvector_1024_25fbf57b-7df8-4b62-a211-5da0acb662ae')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pgvector_1024_25fbf57b-7df8-4b62-a211-5da0acb662ae',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('vector', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('chunk_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('asset_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], name=op.f('pgvector_1024_25fbf57b-7df8-4b62-a211-5da0acb662a_asset_id_fkey')),
    sa.ForeignKeyConstraint(['chunk_id'], ['assetchunk.id'], name=op.f('pgvector_1024_25fbf57b-7df8-4b62-a211-5da0acb662a_chunk_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('pgvector_1024_25fbf57b-7df8-4b62-a211-5da0acb662ae_pkey'))
    )
    op.create_table('celery_taskmeta',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.VARCHAR(length=155), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('result', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('date_done', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('traceback', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=155), autoincrement=False, nullable=True),
    sa.Column('args', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('kwargs', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('worker', sa.VARCHAR(length=155), autoincrement=False, nullable=True),
    sa.Column('retries', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('queue', sa.VARCHAR(length=155), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('celery_taskmeta_pkey')),
    sa.UniqueConstraint('task_id', name=op.f('celery_taskmeta_task_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_celery_taskmeta_date_done'), 'celery_taskmeta', ['date_done'], unique=False)
    op.create_table('celery_tasksetmeta',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('taskset_id', sa.VARCHAR(length=155), autoincrement=False, nullable=True),
    sa.Column('result', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('date_done', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('celery_tasksetmeta_pkey')),
    sa.UniqueConstraint('taskset_id', name=op.f('celery_tasksetmeta_taskset_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_celery_tasksetmeta_date_done'), 'celery_tasksetmeta', ['date_done'], unique=False)
    op.create_table('pgvector_786_25fbf57b-7df8-4b62-a211-5da0acb662ae',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('vector', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('chunk_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('asset_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], name=op.f('pgvector_786_25fbf57b-7df8-4b62-a211-5da0acb662ae_asset_id_fkey')),
    sa.ForeignKeyConstraint(['chunk_id'], ['assetchunk.id'], name=op.f('pgvector_786_25fbf57b-7df8-4b62-a211-5da0acb662ae_chunk_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('pgvector_786_25fbf57b-7df8-4b62-a211-5da0acb662ae_pkey'))
    )
    op.drop_index(op.f('ix_message_session_id'), table_name='message')
    op.drop_table('message')
    op.drop_index(op.f('ix_session_user_id'), table_name='session')
    op.drop_index(op.f('ix_session_project_id'), table_name='session')
    op.drop_index(op.f('ix_session_name'), table_name='session')
    op.drop_table('session')
    # ### end Alembic commands ###
